name: GIS-Helper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pyqt==5.12.3
  - pyshp==2.1.0
  - rasterio==1.1.5
  - fiona==1.8.13
  - numpy==1.19.1
  - descartes==1.1.0
  - shapely==1.7.1
  - pyinstaller==4.0
  - pytest==6.0.1
  - pytest-cov==2.10.1
  - pylint==2.5.3
  - flake8==3.8.3
  - mccabe==0.6.1