name: GIS-Helper
dependencies:
  - python=3.7
  - pyqt
  - pyshp
  - rasterio
  - fiona
  - pyqt
  - numpy
  - descartes
  - shapely
  - pyinstaller
  - pytest
  - pytest-cov
  - pylint
  - flake8
  - mccabe